### ISSUE TITLE
surface linux for vanilla os

### ISSUE THREAD

**Issue by KUKARAF** [Vanilla-OS/desktop-image#202]
### Feature Description

adding kernel support for surface linux 
https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup

### Rationale

huge part of the hardware does not work without the kernel and i fail to see a obvious way of adding it

**Comment by juan11iguel** [comment]
(warning, I am just starting to discover vanilla os so take my _take_ with a grain of salt)

This would probably have to be achieved by creating a custom image by forking this repo and modifying [recipe.yml](https://github.com/Vanilla-OS/desktop-image/blob/dev/recipe.yml)

Here is a draft taking the instructions from [linux-surface - Installation-and-Setup](https://github.com/linux-surface/linux-surface/wiki/Installation-and-Setup#debian--ubuntu)


```yaml
name: Vanilla Desktop
id: desktop

stages:
- id: build
  base: ghcr.io/vanilla-os/core:dev
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
	...
    - name: install-linux-surface
        type: shell
        commands:
        # Import keys
        - wget -qO - https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc | gpg --dearmor | dd of=/etc/apt/trusted.gpg.d/linux-surface.gpg
        # Update repository configuration
        - echo "deb [arch=amd64] https://pkg.surfacelinux.com/debian release main" | tee /etc/apt/sources.list.d/linux-surface.list
        - apt update
        # Install linux-surface kernel and its dependencies
        - apt install linux-image-surface linux-headers-surface libwacom-surface iptsd
        # Install linux-surface bootloader so that the kernel is bootable without disabling secureboot
        - sudo apt install linux-surface-secureboot-mok
        # Post-install instructions
        # Install CPU microcode firmware for the latest CPU updates
        - apt install intel-microcode
```

This probably won't work just as is, and I am unsure how this image would be kept updated as new versions of the base are updated. Maybe this is not the best approach?
